### ISSUE TITLE
Doesn't work with Form Maker Extension

### ISSUE THREAD

**Issue by ITAudioNet** [zero-24/plg_contact_antispamextended#1]
Hi...Your plugin is exactly what I needed and appreciate the fact that you developed it.

We installed it using the Joomla store and enabled it.  I added a derogatory word  (ex. penis) into the blacklist and saved it.

I  went to our "Contact Us" form  on our  website   to test and it still went through.

We are using the most up to date version of Joomla and "Form Maker" for the form

Not sure how your plugin ties in with "Form Maker" for joomla.

Any help would be greatly appreciated?

Thanks

**Comment by zero-24** [comment]
Hi, this plugin right now only integrates into the joomla core contact form.

Please send me details regarding that Form Maker to mail[at]zero24.name and i can take a look whether i can add support for that extension too.

**Comment by zero-24** [comment]
Hi @ITAudioNet 

please confirm that you are working with this extension: https://extensions.joomla.org/extension/form-maker/

I have just tried that extension but it seems (at least in the lite variant) i does not use the joomla form API nor allow any plugins to interact with the forms. Do you use the lite or the pro version? Can you send me to mail[at]zero24.name the contact details from the developer so i can contact him to check whether we can integrate our two extensions.

**Comment by ITAudioNet** [comment]
Yes…I can conform that is what we are working with.  Details below:

Form Maker
Administrator
Component
3.6.9
September 2011
Web Dorado
N/A

10133
Form Maker
Site
Package
3.6.9
September 2011
Web Dorado
N/A

10134
Form Maker Module
Site
Module
3.6.9
January 2011
Web-Dorado
N/A

1013

**Comment by zero-24** [comment]
Hi @ITAudioNet 

Yes as mention above I have tried the lite version and it does not support plugins nor use the joomla form API.

Can you send me to mail[at]zero24.name the contact details from the developer so i can contact him on your behalf to check whether we can integrate our two extensions.

Thanks.

**Comment by ITAudioNet** [comment]
The developer would be my boss and he told me he is using the version listed above for creating forms. I dont know what else to tell you.  Providing some screen shots. 
![screen1](https://user-images.githubusercontent.com/67488294/86412573-4dce5580-bc8d-11ea-9b62-1bb7426330b1.JPG)
![screen2](https://user-images.githubusercontent.com/67488294/86413044-43608b80-bc8e-11ea-942f-4f1107198e46.JPG)

**Comment by zero-24** [comment]
> The developer would be my boss and he told me he is using the version listed above for creating forms. I dont know what else to tell you. Providing some screen shots.

Do you run the lite or the pro version of that extension? Do you have a contact to the developer of that extension? As mention the lite version does not support plugins nor use the joomla form API so we rely on the extension developer to provide us a way to hook into the form submit.

**Comment by zero-24** [comment]
Dear @ITAudioNet for now I will close this issue for the reasons mention above. So please contact the extension developer as he does not seem to use the Joomla Form API for that reason i can not hook into it with my plugin.
